const PIECES=[{id:'S',o:'H',len:2},{id:'A',o:'V',len:2},{id:'B',o:'V',len:3},{id:'C',o:'H',len:2},{id:'D',o:'H',len:3},{id:'E',o:'V',len:2},{id:'F',o:'H',len:2},{id:'G',o:'V',len:2},{id:'H',o:'H',len:2},{id:'I',o:'V',len:2}];
const LEVELS=[
{name:'Langkah pertama',target:3,p:{S:[3,2],A:[0,2],B:[2,0],C:[3,0],D:[0,4],E:[5,0],F:[3,5],G:[1,1],H:[3,3],I:[5,4]}},
{name:'Jalur sempit',target:4,p:{S:[3,2],A:[0,1],B:[2,0],C:[3,0],D:[1,4],E:[5,0],F:[3,5],G:[1,1],H:[3,3],I:[5,4]}},
{name:'Belok kiri',target:4,p:{S:[3,2],A:[0,0],B:[2,0],C:[3,0],D:[1,4],E:[5,1],F:[4,5],G:[1,1],H:[3,3],I:[5,3]}},
{name:'Pintu ganda',target:5,p:{S:[2,2],A:[0,0],B:[2,3],C:[3,0],D:[3,4],E:[5,0],F:[3,5],G:[1,1],H:[3,3],I:[5,2]}},
{name:'Lintasan padat',target:5,p:{S:[3,2],A:[0,2],B:[2,0],C:[3,0],D:[1,4],E:[5,0],F:[0,5],G:[1,1],H:[3,3],I:[5,4]}},
{name:'Tiga penjaga',target:6,p:{S:[2,2],A:[0,0],B:[2,3],C:[3,0],D:[3,4],E:[5,0],F:[3,5],G:[1,0],H:[3,3],I:[5,2]}},
{name:'Jalan memutar',target:7,p:{S:[2,2],A:[0,0],B:[2,3],C:[1,0],D:[3,4],E:[5,0],F:[3,5],G:[1,4],H:[3,3],I:[5,2]}},
{name:'Simpang enam',target:10,p:{S:[0,2],A:[0,0],B:[2,0],C:[3,0],D:[1,4],E:[5,0],F:[4,5],G:[1,0],H:[1,3],I:[5,2]}},
{name:'Kunci silang',target:7,p:{S:[1,2],A:[0,4],B:[2,3],C:[3,0],D:[3,4],E:[5,0],F:[3,5],G:[1,3],H:[3,3],I:[5,2]}},
{name:'Lorong ungu',target:8,p:{S:[0,2],A:[0,0],B:[2,1],C:[3,0],D:[2,4],E:[5,0],F:[3,5],G:[1,3],H:[3,3],I:[5,2]}},
{name:'Dua arah',target:8,p:{S:[2,2],A:[0,2],B:[2,3],C:[3,0],D:[3,4],E:[5,0],F:[0,5],G:[1,0],H:[3,3],I:[5,2]}},
{name:'Gerbang rapat',target:9,p:{S:[0,2],A:[0,0],B:[2,0],C:[3,0],D:[2,4],E:[5,0],F:[2,5],G:[1,0],H:[3,3],I:[5,2]}},
{name:'Putaran akhir',target:9,p:{S:[0,2],A:[0,0],B:[2,1],C:[1,0],D:[3,4],E:[5,0],F:[4,5],G:[1,3],H:[3,3],I:[5,2]}},
{name:'Benteng MEV',target:10,p:{S:[0,2],A:[0,0],B:[2,1],C:[3,0],D:[1,4],E:[5,0],F:[0,5],G:[1,0],H:[3,3],I:[5,4]}},
{name:'Exit terakhir',target:10,p:{S:[0,2],A:[0,0],B:[2,1],C:[3,0],D:[2,4],E:[5,0],F:[0,5],G:[1,0],H:[3,3],I:[5,4]}}
];
const SIZE=6,GOAL_X=4,GOAL_Y=2,$=id=>document.getElementById(id);
let saved;try{saved=JSON.parse(localStorage.getItem('stabiEscapeProgress'))}catch(e){};const progress=saved||{unlocked:1,stars:{},best:{}};
const MAX_HINTS=3,hintUses={};
let levelIndex=0,state=null,moves=0,history=[],selected='S',drag=null;
const copy=s=>Object.fromEntries(Object.entries(s).map(([k,v])=>[k,[...v]]));
const def=id=>PIECES.find(x=>x.id===id);
function occupied(s,ignore){const m=new Map();for(const p of PIECES){if(p.id===ignore)continue;const [x,y]=s[p.id];for(let i=0;i<p.len;i++){const cx=x+(p.o==='H'?i:0),cy=y+(p.o==='V'?i:0);m.set(cx+','+cy,p.id)}}return m}
function canMove(id,d,s=state){if(!d)return false;const p=def(id),[x,y]=s[id],g=occupied(s,id),nx=x+(p.o==='H'?d:0),ny=y+(p.o==='V'?d:0);if(nx<0||ny<0||(p.o==='H'&&nx+p.len>SIZE)||(p.o==='V'&&ny+p.len>SIZE))return false;for(let i=0;i<p.len;i++){const cx=nx+(p.o==='H'?i:0),cy=ny+(p.o==='V'?i:0);if(g.has(cx+','+cy))return false}return true}
function maxMove(id,dir,s=state){let n=0;while(canMove(id,n+dir,s))n+=dir;return n}
function movePiece(id,d,record=true){if(!canMove(id,d))return false;if(record)history.push({state:copy(state),moves});const p=def(id);state[id][p.o==='H'?0:1]+=d;moves++;selected=id;render();if(state.S[0]===GOAL_X&&state.S[1]===GOAL_Y)setTimeout(win,180);return true}
function render(){const board=$('board');board.querySelectorAll('.piece').forEach(el=>el.remove());for(const p of PIECES){const [x,y]=state[p.id],el=document.createElement('div');el.className='piece '+(p.o==='H'?'h':'v')+(p.id==='S'?' stabi':'')+(selected===p.id?' selected':'');el.style.left=(x*100/6)+'%';el.style.top=(y*100/6)+'%';el.style.width=((p.o==='H'?p.len:1)*100/6)+'%';el.style.height=((p.o==='V'?p.len:1)*100/6)+'%';const inner=document.createElement('div');inner.className='piece-inner';inner.textContent=p.id==='S'?'STABI →':p.o==='H'?'SLIPPAGE':'MEV';el.append(inner);board.append(el);el.addEventListener('click',()=>{selected=p.id;render()});el.addEventListener('pointerdown',e=>{selected=p.id;drag={id:p.id,x:e.clientX,y:e.clientY};el.setPointerCapture?.(e.pointerId);render()});el.addEventListener('pointerup',e=>{if(!drag||drag.id!==p.id)return;const r=board.getBoundingClientRect(),cell=r.width/6;let d=p.o==='H'?(e.clientX-drag.x)/cell:(e.clientY-drag.y)/cell;d=Math.round(d);if(d){const sign=Math.sign(d),m=maxMove(p.id,sign),amount=Math.min(Math.abs(d),Math.abs(m))*sign;if(amount)movePiece(p.id,amount)}drag=null})}const L=LEVELS[levelIndex];$('moves').textContent=moves;$('target').textContent=L.target+' langkah';$('best').textContent=progress.best[levelIndex+1]??'—';$('levelTag').textContent='LEVEL '+String(levelIndex+1).padStart(2,'0')+' / 15';$('levelName').textContent=L.name;const p=def(selected);$('neg').textContent=p.o==='H'?'←':'↑';$('pos').textContent=p.o==='H'?'→':'↓';$('neg').disabled=!maxMove(selected,-1);$('pos').disabled=!maxMove(selected,1);$('undo').disabled=!history.length;const remaining=Math.max(0,MAX_HINTS-(hintUses[levelIndex]||0));$('hint').textContent='✦ Kisi-kisi ('+remaining+')';$('hint').disabled=remaining===0}
function loadLevel(i){levelIndex=i;state=copy(LEVELS[i].p);moves=0;history=[];selected='S';$('status').textContent='Pilih balok lalu geser sesuai arahnya.';$('resultOverlay').classList.remove('show');$('levelOverlay').classList.remove('show');render()}
const starsFor=(m,t)=>m<=t?3:m<=t+2?2:1;
function save(){localStorage.setItem('stabiEscapeProgress',JSON.stringify(progress))}
function win(){const n=levelIndex+1,s=starsFor(moves,LEVELS[levelIndex].target);progress.stars[n]=Math.max(progress.stars[n]||0,s);progress.best[n]=progress.best[n]?Math.min(progress.best[n],moves):moves;progress.unlocked=Math.max(progress.unlocked,Math.min(15,n+1));save();$('resultStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);$('resultTitle').textContent=LEVELS[levelIndex].name+' clear!';$('resultText').textContent=moves+' langkah • Best '+progress.best[n]+' • '+s+'/3 bintang';$('nextLevel').style.display=n<15?'block':'none';$('resultOverlay').classList.add('show');buildLevels()}
function buildLevels(){const g=$('levelsGrid');g.innerHTML='';LEVELS.forEach((L,i)=>{const n=i+1,b=document.createElement('button');b.className='lvl'+(n>progress.unlocked?' locked':'');b.disabled=n>progress.unlocked;b.innerHTML=n+'<small>'+('★'.repeat(progress.stars[n]||0))+'</small>';b.onclick=()=>loadLevel(i);g.append(b)})}
function stateKey(s){return PIECES.map(p=>s[p.id].join(',')).join('|')}
function hintSearch(start){const q=[copy(start)],seen=new Set([stateKey(start)]),parent=new Map(),action=new Map();let qi=0,goal=null;while(qi<q.length&&q.length<30000){const cur=q[qi++];if(cur.S[0]===GOAL_X&&cur.S[1]===GOAL_Y){goal=cur;break}for(const p of PIECES)for(const dir of [-1,1]){let d=dir;while(canMove(p.id,d,cur)){const ns=copy(cur);ns[p.id][p.o==='H'?0:1]+=d;const k=stateKey(ns);if(!seen.has(k)){seen.add(k);q.push(ns);parent.set(k,stateKey(cur));action.set(k,{id:p.id,d})}d+=dir}}}if(!goal)return null;const startK=stateKey(start);let k=stateKey(goal),first=null;while(k!==startK){first=action.get(k);k=parent.get(k)}return first}
$('begin').onclick=()=>{$('landing').classList.add('hide');$('game').classList.add('active');loadLevel(Math.max(0,Math.min(14,(progress.unlocked||1)-1)))};
$('levelsBtn').onclick=()=>{$('levelOverlay').classList.add('show');buildLevels()};$('closeLevels').onclick=()=>$('levelOverlay').classList.remove('show');
$('undo').onclick=()=>{const h=history.pop();if(h){state=h.state;moves=h.moves;render()}};$('restart').onclick=()=>loadLevel(levelIndex);$('retry').onclick=()=>loadLevel(levelIndex);$('nextLevel').onclick=()=>loadLevel(Math.min(14,levelIndex+1));
$('neg').onclick=()=>{const d=maxMove(selected,-1);if(d)movePiece(selected,d)};$('pos').onclick=()=>{const d=maxMove(selected,1);if(d)movePiece(selected,d)};
$('hint').onclick=()=>{const n=hintUses[levelIndex]||0;if(n>=MAX_HINTS){$('status').textContent='Kisi-kisi untuk level ini sudah habis.';render();return}hintUses[levelIndex]=n+1;render();$('status').textContent='Mencari satu langkah terbaik…';setTimeout(()=>{const a=hintSearch(state);if(!a){hintUses[levelIndex]=Math.max(0,(hintUses[levelIndex]||1)-1);$('status').textContent='Belum menemukan petunjuk.';render();return}selected=a.id;const p=def(a.id);$('status').textContent='Kisi-kisi: pilih '+(a.id==='S'?'STABI':p.o==='H'?'SLIPPAGE':'MEV')+' lalu geser '+(p.o==='H'?(a.d<0?'ke kiri':'ke kanan'):(a.d<0?'ke atas':'ke bawah'))+'.';render()},20)};
document.addEventListener('keydown',e=>{if(!$('game').classList.contains('active'))return;if(e.key==='z')$('undo').click();const p=def(selected);if(p.o==='H'&&e.key==='ArrowLeft')$('neg').click();if(p.o==='H'&&e.key==='ArrowRight')$('pos').click();if(p.o==='V'&&e.key==='ArrowUp')$('neg').click();if(p.o==='V'&&e.key==='ArrowDown')$('pos').click()});
buildLevels();